name: ct312h_project
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  badges: ^3.1.2
  curved_navigation_bar: ^1.0.6
  provider: ^6.1.2
  clippy_flutter: ^2.0.0-nullsafety.1
  flutter_rating_bar: ^4.0.1
  intl: ^0.20.2
  http: ^1.3.0
  shared_preferences: ^2.5.2
  flutter_dotenv: ^5.2.1
  pocketbase: ^0.22.0
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/tu.jpg
    - assets/giuong.jpg
    - assets/ban.jpg
    - assets/ghe.jpg
    - assets/guong.jpg
